name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/mtcazurekey
          chmod 600 ~/.ssh/mtcazurekey
          ssh-keyscan -H 13.94.185.228 >> ~/.ssh/known_hosts

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/mtcazurekey azureuser@13.94.185.228 << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-python-app
            docker stop my-python-app || true
            docker rm my-python-app || true
            docker run -d --name my-python-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-python-app
          EOF
